<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:47:04</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:47:13</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:47:28</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:47:49</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:48:24</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:49:14</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:49:34</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 14:50:09</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 15:05:55</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3830f0286ab8a8ec67959d1b</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-01-26 15:06:51</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>3830f0286ab8a8ec67959d1b</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 83.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.6636, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
</root>