<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>5c546a9c6894f576653b951c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-28 10:48:51</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>carry_sim_posture.py:120</categoryid><desyncid>5c546a9c6894f576653b951c</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(stand:11296, posture_CarryNothing:11064, posture_CarryObject:11302, posture_CarryNothing:11065) and carry aspects (posture_CarryNothing(11064, None), posture_CarryObject(11302, food_Popcorn_Plain_SP05:0x0b9c11befe53017a), posture_CarryNothing(11065, None)), ')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 151, in _start_carried_linked_posture_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 120, in set_target_linked_posture_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture_state.py", line 154, in __init__KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(stand:11296, posture_CarryNothing:11064, posture_CarryObject:11302, posture_CarryNothing:11065) and carry aspects (posture_CarryNothing(11064, None), posture_CarryObject(11302, food_Popcorn_Plain_SP05:0x0b9c11befe53017a), posture_CarryNothing(11065, None)), 'rtim=0&#13;&#10;Client Session Time: 65.58&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5c546a9c6894f576653b951c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-28 10:53:24</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>carry_sim_posture.py:120</categoryid><desyncid>5c546a9c6894f576653b951c</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(sit:11469, posture_CarryNothing:11381, posture_CarryObject:11470, posture_CarryNothing:11382) and carry aspects (posture_CarryNothing(11381, None), posture_CarryObject(11470, food_Popcorn_Plain_SP05:0x0b9c11beff3a0756), posture_CarryNothing(11382, None)), ')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 151, in _start_carried_linked_posture_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_sim_posture.py", line 120, in set_target_linked_posture_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture_state.py", line 154, in __init__KeyError: 'spec_carry_target PostureSpecVariable.CARRY_TARGET not in var_map:{HAND: (&lt;Hand.LEFT = 1&gt;,)}. Sim posture state PostureState(sit:11469, posture_CarryNothing:11381, posture_CarryObject:11470, posture_CarryNothing:11382) and carry aspects (posture_CarryNothing(11381, None), posture_CarryObject(11470, food_Popcorn_Plain_SP05:0x0b9c11beff3a0756), posture_CarryNothing(11382, None)), 'rtim=0&#13;&#10;Client Session Time: 65.58&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5c546a9c6894f576653b951c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-28 10:59:58</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>interaction_liabilities.py:103</categoryid><desyncid>5c546a9c6894f576653b951c</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: Interaction:  running bed_Nap_Toddler:187799 on object_bedSingle_Toddler_EF48GENbabyCrib:0x0c6811b4d339a523[0]  (guaranteed) is trying to reserve surface space with sim as target. Exception:'object_sim' object has no attribute 'part_owner')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\privacy.py", line 316, in build_privacy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_sim' object has no attribute 'part_owner'&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 6068, in _execute_next_transition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 5816, in _get_next_transition_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_liabilities.py", line 103, in __init__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\privacy.py", line 321, in build_privacyAttributeError: Interaction:  running bed_Nap_Toddler:187799 on object_bedSingle_Toddler_EF48GENbabyCrib:0x0c6811b4d339a523[0]  (guaranteed) is trying to reserve surface space with sim as target. Exception:'object_sim' object has no attribute 'part_owner'rtim=0&#13;&#10;Client Session Time: 65.58&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
</root>