<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>7833e923302f62f16534b201</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-22 17:22:26</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>asm.py:1072</categoryid><desyncid>7833e923302f62f16534b201</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception resuming Element (RuntimeError: ASM :: Carry_GenericObject (HANDLE :: 307573)&gt;: Attempt to traverse between two states (pickup -&gt; exit) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF44FA0F310; to 'object_sim' at 0x00007FF476446810&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'carryObject': (&lt;weakref at 0x00007FF4D6785C00; to 'Prop_University_CradleNotebook' at 0x00007FF47F9A5FD0&gt;, None, &lt;AnimationParticipant.CONTAINER = 102&gt;)}&#13;&#10;source_interaction =  running carry_holdobject:78719 on Prop_University_CradleNotebook:0x0a6411b7718c88c2&#13;&#10;running interaction =  running terrain_putdown:78741 on None)&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 221, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition.py", line 426, in do_transition_animation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\carry_postures.py", line 808, in append_exit_to_arb&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2694, in append_exit_to_arb&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\asm.py", line 1072, in request&#13;&#10;RuntimeError: ASM :: Carry_GenericObject (HANDLE :: 307573)&gt;: Attempt to traverse between two states (pickup -&gt; exit) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF44FA0F310; to 'object_sim' at 0x00007FF476446810&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'carryObject': (&lt;weakref at 0x00007FF4D6785C00; to 'Prop_University_CradleNotebook' at 0x00007FF47F9A5FD0&gt;, None, &lt;AnimationParticipant.CONTAINER = 102&gt;)}&#13;&#10;source_interaction =  running carry_holdobject:78719 on Prop_University_CradleNotebook:0x0a6411b7718c88c2running interaction =  running terrain_putdown:78741 on Nonertim=0&#13;&#10;Client Session Time: 52.40&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>7833e923302f62f16534b201</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-22 17:57:28</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>animation_element.py:185</categoryid><desyncid>7833e923302f62f16534b201</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: ASM :: Motion_Based_Gaming (HANDLE :: 400643)&gt;: Attempt to traverse between two states (FamilyLoop -&gt; PuzzleLoop) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF44C0EAE68; to 'object_sim' at 0x00007FF47BFD7CD0&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'gameMat': (&lt;weakref at 0x00007FF4D39A5120; to 'object_gameMotionMatGuruEvent_01' at 0x00007FF48F924B90&gt;, '0', &lt;AnimationParticipant.TARGET = 103&gt;)} (debug context:  running motionBasedGaming_play_family:92584 on object_gameMotionMatGuruEvent_01:0x0cf80406c38d0000[0]))&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\animation_element.py", line 185, in do_begin&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\asm.py", line 1072, in requestRuntimeError: ASM :: Motion_Based_Gaming (HANDLE :: 400643)&gt;: Attempt to traverse between two states (FamilyLoop -&gt; PuzzleLoop) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF44C0EAE68; to 'object_sim' at 0x00007FF47BFD7CD0&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'gameMat': (&lt;weakref at 0x00007FF4D39A5120; to 'object_gameMotionMatGuruEvent_01' at 0x00007FF48F924B90&gt;, '0', &lt;AnimationParticipant.TARGET = 103&gt;)} (debug context:  running motionBasedGaming_play_family:92584 on object_gameMotionMatGuruEvent_01:0x0cf80406c38d0000[0])rtim=0&#13;&#10;Client Session Time: 52.40&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>7833e923302f62f16534b201</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-22 18:47:32</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>interaction_liabilities.py:103</categoryid><desyncid>7833e923302f62f16534b201</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: Interaction:  running bed_Nap_Toddler:124193 on object_bedSingle_Toddler_EF48GENbabyCrib:0x0c6811b4d339a523[0]  (guaranteed) is trying to reserve surface space with sim as target. Exception:'object_sim' object has no attribute 'part_owner')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\privacy.py", line 316, in build_privacy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_sim' object has no attribute 'part_owner'&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 6068, in _execute_next_transition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 5816, in _get_next_transition_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_liabilities.py", line 103, in __init__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\privacy.py", line 321, in build_privacyAttributeError: Interaction:  running bed_Nap_Toddler:124193 on object_bedSingle_Toddler_EF48GENbabyCrib:0x0c6811b4d339a523[0]  (guaranteed) is trying to reserve surface space with sim as target. Exception:'object_sim' object has no attribute 'part_owner'rtim=0&#13;&#10;Client Session Time: 52.40&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
</root>