<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 16:21:16</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>animation_element.py:185</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: ASM :: Motion_Based_Gaming (HANDLE :: 234055)&gt;: Attempt to traverse between two states (Sports -&gt; PuzzleLoop) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF4D5D013C0; to 'object_sim' at 0x00007FF463CE0250&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'gameMat': (&lt;weakref at 0x00007FF4DF520EF0; to 'object_gameMotionMatGuruEvent_01' at 0x00007FF45AD44A90&gt;, '0', &lt;AnimationParticipant.TARGET = 103&gt;)} (debug context:  running motionBasedGaming_play_sports:70708 on object_gameMotionMatGuruEvent_01:0x0e44041b8f8e0000[0]))&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\animation_element.py", line 185, in do_begin&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\animation\asm.py", line 1072, in requestRuntimeError: ASM :: Motion_Based_Gaming (HANDLE :: 234055)&gt;: Attempt to traverse between two states (Sports -&gt; PuzzleLoop) where no valid path exists! Actors {'x': (&lt;weakref at 0x00007FF4D5D013C0; to 'object_sim' at 0x00007FF463CE0250&gt;, None, &lt;AnimationParticipant.ACTOR = 101&gt;), 'gameMat': (&lt;weakref at 0x00007FF4DF520EF0; to 'object_gameMotionMatGuruEvent_01' at 0x00007FF45AD44A90&gt;, '0', &lt;AnimationParticipant.TARGET = 103&gt;)} (debug context:  running motionBasedGaming_play_sports:70708 on object_gameMotionMatGuruEvent_01:0x0e44041b8f8e0000[0])rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 16:52:22</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>transition_sequence.py:2979</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception resuming Element (AssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed))&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 221, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4043, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 768, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1584, in run_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3558, in _build_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3304, in _build_and_log_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3370, in _build_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2820, in get_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2979, in _get_transitions_for_sim&#13;&#10;  File "postures\posture_graph.py", line 5162, in postures.posture_graph.PostureGraphService.get_segmented_pathsAssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed)rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 16:52:22</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>posture_graph.py:5162</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running TYAE_CheckOn_Infant_RoleStateActivate:89154 on , cancel_reason_msg is object destroyed: (AssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed))&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2979, in _get_transitions_for_sim&#13;&#10;  File "postures\posture_graph.py", line 5162, in postures.posture_graph.PostureGraphService.get_segmented_paths&#13;&#10;AssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed)rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 16:52:22</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>posture_graph.py:5162</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running TYAE_CheckOn_Infant_RoleStateActivate:88980 on , cancel_reason_msg is object destroyed: (AssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed))&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2979, in _get_transitions_for_sim&#13;&#10;  File "postures\posture_graph.py", line 5162, in postures.posture_graph.PostureGraphService.get_segmented_paths&#13;&#10;AssertionError: Source spec not in the posture graph: carried_sim@ for interaction:  running socialSuperInteraction_CarryPickUp_Infant:89207 on   (guaranteed)rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 17:52:25</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:115642 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 17:57:48</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:119216 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 17:58:59</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:119576 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 17:59:59</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:119915 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 18:08:55</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:123660 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 18:09:27</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:406</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_interactions.py", line 482, in _do_perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 212, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 1333, in append&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4415, in on_added_to_queue&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7453, in on_added_to_queue&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5541, in _entered_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7508, in _entered_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5501, in _acquire_liabilities&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5529, in release_liabilities&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\tunable.py", line 649, in transfer&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5387, in priority&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 1545, in on_element_priority_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Lib\contextlib.py", line 119, in __exit__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 900, in _head_change_watcher&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 984, in _get_head&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 345, in get_next_unblocked_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3047, in get_sims_with_invalid_paths&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3003, in _generate_connectivity&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1537, in compute_transition_connectivity&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1584, in run_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3520, in _build_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3304, in _build_and_log_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3370, in _build_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2820, in get_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2878, in _get_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2244, in _get_constraint_for_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 4438, in constraint_intersection&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 4314, in constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_locationAttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 18:36:43</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:375</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running aggregateSuperInteraction_CarriedSim_PutDown_ToddlerPet:137763 on , cancel_reason_msg is Interaction Auto Completed: (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_location&#13;&#10;AttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
<report><version>2</version><sessionid>bffcae5b771ee07c6531dda5</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-10-20 18:37:10</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>put_down_sim_interactions.py:406</categoryid><desyncid>bffcae5b771ee07c6531dda5</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'translation')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_interactions.py", line 482, in _do_perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 212, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 1333, in append&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4415, in on_added_to_queue&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7453, in on_added_to_queue&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5541, in _entered_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7508, in _entered_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5501, in _acquire_liabilities&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5529, in release_liabilities&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\tunable.py", line 649, in transfer&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5387, in priority&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 1545, in on_element_priority_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Lib\contextlib.py", line 119, in __exit__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 900, in _head_change_watcher&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 984, in _get_head&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 345, in get_next_unblocked_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3047, in get_sims_with_invalid_paths&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3003, in _generate_connectivity&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1537, in compute_transition_connectivity&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1584, in run_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3520, in _build_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3304, in _build_and_log_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3370, in _build_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2820, in get_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2878, in _get_transitions_for_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 2244, in _get_constraint_for_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 4438, in constraint_intersection&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 4314, in constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 416, in _constraint_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 406, in _get_best_location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\carry\put_down_sim_interactions.py", line 375, in _adjust_locationAttributeError: 'NoneType' object has no attribute 'translation'rtim=0&#13;&#10;ClientInfo isn't here</desyncdata></report>
</root>